### ISSUE TITLE
Switch to using Ansible for remote command execution

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/leapp#13]
`leapp-tool.py` current uses `ssh` directly for remote command execution, which has some critical limitations:

- it's hardcoded to access the remote system as the `vagrant` user
- it's hardcoded to use the predefined leappto testing key
- all the other ssh settings are also hardcoded

Rather than making these configurable natively in leapp-to, it makes more sense to migrate to using the higher level Ansible constructs for remote command execution, and then setting up suitable "demo" and "integration-test" Ansible configurations for use with the Cockpit plugin and the integration tests.

**Comment by ncoghlan** [comment]
Looking up the environment settings we're likely to want in https://github.com/ansible/ansible/blob/devel/lib/ansible/constants.py and http://docs.ansible.com/ansible/intro_configuration.html, it seems that we can use `ANSIBLE_REMOTE_USER` to set the user to connect as: http://docs.ansible.com/ansible/intro_configuration.html#remote-user

However, it *really* wants to use `ssh-agent` for SSH key management and doesn't offer a separate option: http://docs.ansible.com/ansible/intro_adhoc.html

So if we were to switch to using Ansible rather than plain ssh, we'd want to either:

- go back to the idea of loading the *user's* default SSH keys into the demo and testing VMs (perhaps based on writing the output of `ssh-add -L` to a known location rather than assuming where to find the user's public keys)
- load the predefined public key into the SSH agent by limiting read access to the current user (so `ssh-add` will load it), loading it in with a defined lifetime when the integration tests start, and then explicitly unloading it when the integration tests are done

**Comment by pcahyna** [comment]
> it really wants to use ssh-agent for SSH key management and doesn't offer a separate option

What about

```
ansible_ssh_private_key_file
    Private key file used by ssh. Useful if using multiple keys and you don’t want to use SSH agent.
```
(http://docs.ansible.com/ansible/intro_inventory.html#list-of-behavioral-inventory-parameters)

**Comment by ncoghlan** [comment]
@pcahyna Ah, nice!

Following some of the links from that page, I also note that there's an existing dynamic inventory script available for Vagrant: http://docs.ansible.com/ansible/intro_dynamic_inventory.html#other-inventory-scripts

By using Ansible, we'd also be able to put all the other settings we need for the demo and the tests in a suitable ansible.cfg file, and ensure the working directory is set appropriately: http://docs.ansible.com/ansible/intro_configuration.html

So I think this is definitely the way we want to go to start decoupling LeApp from its current reliance on Vagrant and libvirt.

**Comment by pcahyna** [comment]
Note that currently leap-tool copies the data using a pipe, thus avoiding a temporary file. Would ansible be able to do that? Or is a (potentially large, as it contains the complete state of the source VM, IIUC) temporary file acceptable?

**Comment by ncoghlan** [comment]
Looks like the answer to @pcahyna's question is "not currently": https://github.com/ansible/ansible/issues/14380

However, I think there's a related architectural question that we're going to need to resolve there anway: at the moment, we do an immediate "live deploy" of the containerised VM snapshot, but that's unlikely to be adequate long term.

Instead, for a more flexible management flow, we're going to need to break that into two steps:

- create some form of binary artifact that represents the containerised VM snapshot (both the base image and the state snapshot)
- deploy the image and state snapshot

There's actually a control flow branch for this in `leapp-tool` (when you don't specify `--target`), but at the moment it just raises `NotImplementedError`.

**Comment by shaded-enmity** [comment]
Yup, we're tracking the binary artifact stuff here: https://trello.com/c/Xnz9wDjV/26-export-machine-into-a-tarball

**Comment by ncoghlan** [comment]
@shaded-enmity Could be handy to have a public issue with any related design notes for future reference.

**Comment by vinzenz** [comment]
I guess this is obsolete now since we actually do use ansible for remote execution leapp now
