### ISSUE TITLE
Investigate using `ansible-role-scl` for SCL management

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/leapp#142]
@robynbergeron recently pointed me towards https://github.com/smbambling/ansible-role-scl as a potential option for declaratively installing and configuring different SCLs in a distro-independent way.

This seems like a good way for us to go, since it means that if we need to make any improvements, they'll be to a common role shared across multiple projects, rather than being specific to LeApp.

**Comment by shaded-enmity** [comment]
I considered this (it was even in a comment somewhere for a while), but eventually settled for installing the SCL package and repo manually to not introduce dependencies on `ansible-galaxy`. 

+1 but would give this low prio as the current way works well for CentOS and I know that @vmindru has his plans for refactoring Ansible stuff.
