### ISSUE TITLE
Le-App cockpit plugin must present errors in a distinguishable manner

### ISSUE THREAD

**Issue by vmindru** [leapp-to/leapp#143]
Currently, when something unexpected happens in the cockpit the error is printed in the text status area with same font color and manner as a success, this might be misleading the error must be somehow promoted in a clear format, e.g. print the error message in Bold Red and make the "Migrate" button not available.

**Comment by vmindru** [comment]
e.g. check the image out http://imgur.com/a/qK4mz the text is not noticeable especially that from other part's of the page one might belie all is good and the migrate button is available.

**Comment by ncoghlan** [comment]
This was also a bit challenging in the test suite - the integration test is currently looking for particular text showing up, but it would be more robust if it could look specifically for an error div or similar to determine if a command failed.
