### ISSUE TITLE
Automatically restart containers when target machine restarted

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/leapp#152]
Currently, a macrocontainer created by migrate-machine *won't* automatically restart when the target systems is restarted.

That's probably not what we want - we should be configuring either systemd or the container engine to automatically restart the container on system boot.

**Comment by shaded-enmity** [comment]
+1 for a system service as the notion of "container engine/daemon" is rather ill-defined and pretty much Docker specific.

**Comment by vmindru** [comment]
https://github.com/leapp-to/leapp/pull/210
