### ISSUE TITLE
rename repo into "leapp" to match the package name

### ISSUE THREAD

**Issue by vmindru** [leapp-to/leapp#207]
rename repo into "leapp" to match the product, we are over the prototype phase already and about to release v0.1

**Comment by ncoghlan** [comment]
When do we want to do this? We should do it before 0.1, so we can use the stable repo name in the release metadata.

**Comment by vmindru** [comment]
I will raise this with the team today, I guess we will do this during this week.

**Comment by vmindru** [comment]
https://github.com/leapp-to/leapp/pull/241
