### ISSUE TITLE
Avoid pointlessly installing Ansible (et al) twice in CI

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/leapp#220]
To ensure that we always get a consistent version of our dependencies, we're currently using `pipenv` to manage the Python virtual environment in our CI setup.

Unfortunately, this isn't really the ideal configuration, since it means that we end up installing a bunch of dependencies (including ansible itself) twice: once inside the virtual environment, and once outside it. And because the system level packages don't populate the Python wheel cache, the second installation ends up being quite slow.

The original concept below turned out to be based on a flawed assumption (since we're using the Python 3.5 SCL to run the test suite, we don't have access to the system site packages anyway), but that turned out not to matter: the duplicated components were ones the test suite only accesses via their CLI anyway, so we were able to just drop them from `Pipfile` and make it a requirement that they be set up externally.

---
Original concept:

Since we tightly control the CI execution environment, it would make sense to use the `--system-site-packages` option to eliminate the duplication, but that isn't currently supported in `pipenv` (for good reasons): https://github.com/kennethreitz/pipenv/issues/419

So while I still think `pipenv` is useful to create a completely self-contained local development environment, I'm starting to think that for CI purposes we're likely to be better off doing something like the following:

- Update `Pipfile` to pin the versions for components that we're expecting to get from the EPEL/RHEL/CentOS repos
- Update the CI Ansible roles to skip calling `pipenv install`, and instead call `pipenv lock --requirements` (alternatively: we could stop checking in `Pipfile.lock` and instead check in `integration-tests/requirements.txt`. If we went that way, we wouldn't need `pipenv` in the CI environment at all, and using it locally would also become entirely optional)
- Change the CI Ansible roles to set up the venv natively with `python -m venv --system-site-packages` rather than `pipenv`

**Comment by vmindru** [comment]
+1 I think in CI we should install system packages only, this is the closest approach a user would do. I am doing this in CD and the only one I have to install in a non-standard way is python-nmap.

**Comment by ncoghlan** [comment]
We'll have more Python-specific dependencies in CI to run the test suite itself (behave, splinter, etc), but we should be able to rely on at least the system provided `ansible` and the system provided `requests`.

Getting to the point where `pipsi` is optional and we instead use the just-built RPM will also be helpful.

**Comment by ncoghlan** [comment]
I've started exploring our options along these lines in #229, and realised there's another limitation keeping us from relying on system packages for Python level imports: we run the tests inside a Software Collection anyway.

So the actual problem here is that some of the things we use solely via their CLI (`ansible`, `pipsi`) are also listed as dependencies in `Pipfile` for ease of setting up local development environments.

That's then leading to redundant work in CI, as we get a second copy of the relevant CLI packages that we don't actually need. We're also double isolating the test environment, since we activate the SCL *and* we then activate a Python virtual environment inside it.

So I'm really starting to think that rather than using the `pipenv` model, we'd be better off with the `pip-tools` `requirements.in` model where we better separate our "for CI testing" dependencies from our "for local development" dependencies (since in CI we know we're going to be installing things like `ansible` as system packages, but I'd prefer to avoid requiring that for local development).

**Comment by ncoghlan** [comment]
I've also updated the issue title here to state the goal (stop installing things like Ansible twice in CI), rather than a particular strategy for achieving that (like skipping the use of pipenv)

**Comment by ncoghlan** [comment]
#229 now completely drops the use of `pipenv` from the CI, and ensures that things the test suite only accesses via their CLI (like Ansible and pipsi) are only installed once rather than twice.

Net effect is to reduce the config time for the Python level dependencies from 5 minutes or more to around 30 seconds (and it would likely be even faster if CentOS CI were to offer a local PyPI cache)
