### ISSUE TITLE
Idea: multiple instances of integration testing VMs

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/leapp#26]
The local VM creation code in the integration testing setup currently has the limitation that it only supports one instance of any given VM definition - attempts to create more would conflict on various things like the hostname and the libvirt machine name.

While that's fine for now, we may find it limiting later, so I started this issue to collect some notes on how to do it.

### Static multi-machine Vagrant definitions

The most common way to do multi-machine Vagrant definitions appears to be to define a static `NODE_COUNT` and then just loop in the Vagrantfile's Ruby code, using the loop variable as needed to avoid name and resource conflicts

### Dynamic multi-machine Vagrant definitions

The simplest way to make that dynamically configurable is to read `NODE_COUNT` from an environment variable, and default to `1` if it's not defined. (e.g. `NODE_COUNT = ENV.fetch('LEAPP_TEST_VM_COUNT', 1)`.

The relevant test helper would then need to set `LEAPP_TEST_VM_COUNT` appropriately before calling `vagrant`.

**Comment by shaded-enmity** [comment]
+1 for the Dynamic way.

**Comment by ncoghlan** [comment]
The problem I see with both of the above options is that neither of them really aligns with the way the "Given the local virtual machines" test step currently works. For each VM, that step accepts the following settings:

* `name`: the name used for the VM in test steps (never passed to Vagrant)
* `definition`: the directory name inside `integration-tests/vmdefs`
* `ensure_fresh`: whether to destroy an existing VM instead of re-using it

In a scenario definition, it looks like this:

```
   Given the local virtual machines:
         | name       | definition          | ensure_fresh |
         | app-source | centos6-guest-httpd | no           |
         | target     | centos7-target      | no           |
    When app-source is redeployed to target as a macrocontainer
    Then ...
```

Adding a "node count" to that would require some way of mangling names at the test case level, which doesn't seem ideal given that the within-test-case names are intended to be entirely independent of the underlying VM provisioning.

However, something that *would* work is to allow for an `.instance` suffix on the definitions that is used to vary the exact VM name and hostname used:

```
   Given the local virtual machines:
         | name       | definition          | ensure_fresh |
         | app-source | centos6-guest-httpd | no           |
         | target1    | centos7-target      | no           |
         | target2    | centos7-target.2      | no           |
    When app-source is redeployed to target1 as a macrocontainer
     And app-source is redeployed to target2 as a macrocontainer
    Then ...
```

Similar to the dynamic node count case, the instance identifier would be passed to the Vagrantfile as an environment variable (e.g. `INSTANCE_ID = ENV.fetch('LEAPP_TEST_VM_INSTANCE', '1')`

**Comment by shaded-enmity** [comment]
Could we establish a well known names for the VMs in some pre- step, and then reference them using templating in the scenario? (Not sure if it's even possible to template Gherkin/Behave scenarios).

**Comment by ncoghlan** [comment]
Yes, you can use Scenario Outlines: https://jenisys.github.io/behave.example/tutorials/tutorial04.html

That doesn't change the basic question around what we want scenario *writers* to need to know about how VM provisioning works, though - I'd really like to keep the property where all the names used in test steps are listed directly in the VM table, without scenario writers needing to know much about exactly how the provisioning works.

I did think of a syntax that might work for that purpose using the "NODE_COUNT" approach:

```
   Given the local virtual machines:
         | name        | definition          | ensure_fresh |
         | app-source  | centos6-guest-httpd | no           |
         | target[1,2] | centos7-target      | no           |
    When app-source is redeployed to target1 as a macrocontainer
     And app-source is redeployed to target2 as a macrocontainer
    Then ...
```

```
   Given the local virtual machines:
         | name       | definition          | ensure_fresh |
         | app-[A,B]  | centos6-guest-httpd | no           |
         | target     | centos7-target      | no           |
    When app-A is redeployed to target as a macrocontainer
     And app-B is redeployed to target as a macrocontainer
    Then ...
```

Specifically, names could allow an optional comma-separated list of suffixes, and the step definition would understand that, set the node count to the appropriate value, and then map prefix+suffix to the corresponding VM instance internally.

**Comment by ncoghlan** [comment]
Marking this as deferred until we have a test scenario that actually needs it.
