### ISSUE TITLE
Improve the target container runtime availability check

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/leapp#260]
The initial container runtime availability check just ensures that `docker info` works on the target system.

This isn't entirely adequate, as we also want to check whether or not the container runtime is:

1. Running locally (so it can mount persistent volumes from the target host)
2. Scheduled to start automatically when the server starts (as if it isn't, we can't promise that we'll be able to automatically start containers when the server restarts)

**Comment by vinzenz** [comment]
Closing this issue - As this is no longer applicable
