### ISSUE TITLE
Investigate `daiquiri` for logging configuration

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/leapp#262]
OpenStack's @jd just extracted a useful helper module from the [Gnocchi](https://github.com/gnocchixyz/gnocchi) time series database to help make it easy to set up Python applications with Linux-friendly defaults: https://julien.danjou.info/blog/python-logging-easy-with-daiquiri

Assuming we can settle on a good way to manage Python level runtime dependencies across distro versions (see #126 for discussion of that), then it seems to me that this could be a nice way to inherit some sensible defaults rather than setting up our own from scratch.

**Comment by ncoghlan** [comment]
RPMs are also expected soonish, so we could potentially also just include the RPM in the LeApp COPR even without figuring out the Python level dependency management concerns: https://twitter.com/juldanjou/status/882503765810663425

**Comment by vinzenz** [comment]
Considering that it is not packaged for RHEL just yet and the architecture changed significantly since this idea came up we will close this and keep it in mind if there is some use case that makes this more relevant.
