### ISSUE TITLE
Problem trying to create workflow on Centos7

### ISSUE THREAD

**Issue by artmello** [leapp-to/leapp#314]
While developing some actors, I am having some issues trying to follow the documentation about [Working with Workflows](http://leapp.readthedocs.io/en/latest/working-with-workflows.html). All this is being executed in a CentOS7 machine, with EPEL enabled and virtualized with Vagrant box "centos/7" and libvirt. 
By default, CentOS7 has this version of Python2.7
```
$ /usr/bin/python2.7 --version
Python 2.7.5
```
Following the steps on documentation
```
$ cd devel/
[devel]$ virtualenv -p /usr/bin/python2.7 tut-2.7.5
(...)
[devel]$ . tut-2.7.5/bin/activate
(tut-2.7.5)[devel]$ pip install git+https://github.com/leapp-to/leapp
(...)
(tut-2.7.5)[devel]$ snactor new-project tutorial-2.7.5
New project tutorial-2.7.5 has been created in /home/vagrant/devel/tutorial-2.7.5
(tut-2.7.5)[devel]$ cd tutorial-2.7.5/
(tut-2.7.5)[tutorial-2.7.5]$ snactor workflow new Example
(tut-2.7.5)[tutorial-2.7.5]$ ls -la
total 0
drwxrwxr-x. 3 vagrant vagrant 20 May  5 02:40 .
drwxrwxr-x. 4 vagrant vagrant 45 May  5 02:40 ..
drwxrwxr-x. 2 vagrant vagrant 36 May  5 02:40 .leapp
(tut-2.7.5)[tutorial-2.7.5]$ python --version
Python 2.7.5
(tut-2.7.5)[tutorial-2.7.5]$ deactivate
```
Nothing seems to happen. Since I am able to create workflows in Fedora 27, my best guess is that is a problem with Python 2.7.5. So, I built Python 2.7.14 from source on the same CentOS7 machine
```
$ /usr/local/bin/python2.7 --version
Python 2.7.14
```
And know running the same steps from documentation
```
$ cd devel/
[devel]$ virtualenv -p /usr/local/bin/python2.7 tut-2.7.14
(...)
[devel]$ . tut-2.7.14/bin/activate
(tut-2.7.14)[devel]$ pip install git+https://github.com/leapp-to/leapp
(...)
(tut-2.7.14)[devel]$ snactor new-project tutorial-2.7.14
New project tutorial-2.7.14 has been created in /home/vagrant/devel/tutorial-2.7.14
(tut-2.7.14)[devel]$ cd tutorial-2.7.14/
(tut-2.7.14)[tutorial-2.7.14]$ snactor workflow new Example
New tag ExampleWorkflow has been created in /home/vagrant/devel/tutorial-2.7.14/tags/exampleworkflow.py
New workflow Example has been created in /home/vagrant/devel/tutorial-2.7.14/workflows/example.py
(tut-2.7.14)[tutorial-2.7.14]$ ls -la
total 0
drwxrwxr-x. 5 vagrant vagrant 49 May  5 02:48 .
drwxrwxr-x. 6 vagrant vagrant 86 May  5 02:48 ..
drwxrwxr-x. 2 vagrant vagrant 36 May  5 02:48 .leapp
drwxrwxr-x. 2 vagrant vagrant 32 May  5 02:48 tags
drwxrwxr-x. 2 vagrant vagrant 24 May  5 02:48 workflows
(tut-2.7.14)[tutorial-2.7.14]$ python --version
Python 2.7.14
(tut-2.7.14)[tutorial-2.7.14]$ deactivate
```
It seems to work as expected.
It is not clear to me how much of a impact this would have in real world, if it is just a problem about creating a workflow or if it also impacts running them on old versions of Python2.7. But, if it is in fact a problem with Python version, we could mention that on documentation.

**Comment by vinzenz** [comment]
Thanks for this awesome report again - It got addressed in https://github.com/leapp-to/leapp/commit/bc6963eef0d02b248da84b632dd4e9c38b06e03f and should be fixed now - If you find any other problems please let me know :-)
