### ISSUE TITLE
Document available Ansible roles and VM definitions

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/leapp#34]
As we start building out the integration tests and the demo, we're accumulating a range of predefined Ansible roles and VM definitions. It would be good to have short, readily accessible summaries of which roles and VMs we're already defined, so developers don't reinvent them unnecessarily.

Suggested layout:

- summarise Ansible roles in `ansible_roles/README.md`
- summarise demo VMs in `demo/vmdefs/README.md`
- summarise testing VMs in `integration-tests/vmdefs/README.md`
- add suitable links to `integration-tests/README.md`
- add suitable links to `README.md`

We may also want to move the instructions for running and updating the demo from the main README.md into a `demo/README.md` file, but that doesn't necessarily have to be done here.

**Comment by vinzenz** [comment]
we got rid of most of these therefore this is obsolete
