### ISSUE TITLE
Use LEAPP_DEMO_SUBNET and LEAPP_TEST_SUBNET env vars in Vagrant files

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/leapp#45]
The demo vagrant files currently use DST_IP_ADDR and SRC_IP_ADDR to override the addresses for the target CentOS 7 VM and the source CentOS 6 app VM respectively.

This doesn't generalise well to additional machines, and also doesn't help with the integration testing VMs, so we should instead switch to a configurable private subnet definition.

To avoid address conflicts, we should use different subnets for the demo VMs and the integration testing VMs:

- `LEAPP_DEMO_SUBNET` for demo VMs
- `LEAPP_TEST_SUBNET` for test VMs

**Comment by pcahyna** [comment]
The host parts of the IP addresses would be hardcoded?

**Comment by ncoghlan** [comment]
Aye, at least for now - we're only talking a handful of machines, so we can just keep them distinct manually.
